// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobuf;

/**
 * Protobuf type {@code AnnouncementProto}
 */
public final class AnnouncementProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AnnouncementProto)
    AnnouncementProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnnouncementProto.newBuilder() to construct.
  private AnnouncementProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnnouncementProto() {
    petOwnerEmail_ = "";
    description_ = "";
    timeStart_ = "";
    timeFinish_ = "";
    postalCode_ = "";
    dateOfCreation_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnnouncementProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnnouncementProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            petOwnerEmail_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            timeStart_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            timeFinish_ = s;
            break;
          }
          case 42: {
            origin.protobuf.PetProto.Builder subBuilder = null;
            if (pet_ != null) {
              subBuilder = pet_.toBuilder();
            }
            pet_ = input.readMessage(origin.protobuf.PetProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pet_);
              pet_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            postalCode_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            dateOfCreation_ = s;
            break;
          }
          case 64: {

            id_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return origin.protobuf.Protobuf.internal_static_AnnouncementProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return origin.protobuf.Protobuf.internal_static_AnnouncementProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            origin.protobuf.AnnouncementProto.class, origin.protobuf.AnnouncementProto.Builder.class);
  }

  public static final int PETOWNEREMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object petOwnerEmail_;
  /**
   * <code>string petOwnerEmail = 1;</code>
   * @return The petOwnerEmail.
   */
  @java.lang.Override
  public java.lang.String getPetOwnerEmail() {
    java.lang.Object ref = petOwnerEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      petOwnerEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string petOwnerEmail = 1;</code>
   * @return The bytes for petOwnerEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPetOwnerEmailBytes() {
    java.lang.Object ref = petOwnerEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      petOwnerEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTART_FIELD_NUMBER = 3;
  private volatile java.lang.Object timeStart_;
  /**
   * <code>string timeStart = 3;</code>
   * @return The timeStart.
   */
  @java.lang.Override
  public java.lang.String getTimeStart() {
    java.lang.Object ref = timeStart_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeStart_ = s;
      return s;
    }
  }
  /**
   * <code>string timeStart = 3;</code>
   * @return The bytes for timeStart.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeStartBytes() {
    java.lang.Object ref = timeStart_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeStart_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEFINISH_FIELD_NUMBER = 4;
  private volatile java.lang.Object timeFinish_;
  /**
   * <code>string timeFinish = 4;</code>
   * @return The timeFinish.
   */
  @java.lang.Override
  public java.lang.String getTimeFinish() {
    java.lang.Object ref = timeFinish_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeFinish_ = s;
      return s;
    }
  }
  /**
   * <code>string timeFinish = 4;</code>
   * @return The bytes for timeFinish.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeFinishBytes() {
    java.lang.Object ref = timeFinish_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeFinish_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PET_FIELD_NUMBER = 5;
  private origin.protobuf.PetProto pet_;
  /**
   * <code>.PetProto pet = 5;</code>
   * @return Whether the pet field is set.
   */
  @java.lang.Override
  public boolean hasPet() {
    return pet_ != null;
  }
  /**
   * <code>.PetProto pet = 5;</code>
   * @return The pet.
   */
  @java.lang.Override
  public origin.protobuf.PetProto getPet() {
    return pet_ == null ? origin.protobuf.PetProto.getDefaultInstance() : pet_;
  }
  /**
   * <code>.PetProto pet = 5;</code>
   */
  @java.lang.Override
  public origin.protobuf.PetProtoOrBuilder getPetOrBuilder() {
    return getPet();
  }

  public static final int POSTALCODE_FIELD_NUMBER = 6;
  private volatile java.lang.Object postalCode_;
  /**
   * <code>string postalCode = 6;</code>
   * @return The postalCode.
   */
  @java.lang.Override
  public java.lang.String getPostalCode() {
    java.lang.Object ref = postalCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postalCode_ = s;
      return s;
    }
  }
  /**
   * <code>string postalCode = 6;</code>
   * @return The bytes for postalCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPostalCodeBytes() {
    java.lang.Object ref = postalCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postalCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATEOFCREATION_FIELD_NUMBER = 7;
  private volatile java.lang.Object dateOfCreation_;
  /**
   * <code>string dateOfCreation = 7;</code>
   * @return The dateOfCreation.
   */
  @java.lang.Override
  public java.lang.String getDateOfCreation() {
    java.lang.Object ref = dateOfCreation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateOfCreation_ = s;
      return s;
    }
  }
  /**
   * <code>string dateOfCreation = 7;</code>
   * @return The bytes for dateOfCreation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateOfCreationBytes() {
    java.lang.Object ref = dateOfCreation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateOfCreation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 8;
  private int id_;
  /**
   * <code>int32 id = 8;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petOwnerEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, petOwnerEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStart_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timeStart_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeFinish_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, timeFinish_);
    }
    if (pet_ != null) {
      output.writeMessage(5, getPet());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postalCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, postalCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfCreation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, dateOfCreation_);
    }
    if (id_ != 0) {
      output.writeInt32(8, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petOwnerEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, petOwnerEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStart_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timeStart_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeFinish_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, timeFinish_);
    }
    if (pet_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPet());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postalCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, postalCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfCreation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, dateOfCreation_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof origin.protobuf.AnnouncementProto)) {
      return super.equals(obj);
    }
    origin.protobuf.AnnouncementProto other = (origin.protobuf.AnnouncementProto) obj;

    if (!getPetOwnerEmail()
        .equals(other.getPetOwnerEmail())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getTimeStart()
        .equals(other.getTimeStart())) return false;
    if (!getTimeFinish()
        .equals(other.getTimeFinish())) return false;
    if (hasPet() != other.hasPet()) return false;
    if (hasPet()) {
      if (!getPet()
          .equals(other.getPet())) return false;
    }
    if (!getPostalCode()
        .equals(other.getPostalCode())) return false;
    if (!getDateOfCreation()
        .equals(other.getDateOfCreation())) return false;
    if (getId()
        != other.getId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PETOWNEREMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getPetOwnerEmail().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + TIMESTART_FIELD_NUMBER;
    hash = (53 * hash) + getTimeStart().hashCode();
    hash = (37 * hash) + TIMEFINISH_FIELD_NUMBER;
    hash = (53 * hash) + getTimeFinish().hashCode();
    if (hasPet()) {
      hash = (37 * hash) + PET_FIELD_NUMBER;
      hash = (53 * hash) + getPet().hashCode();
    }
    hash = (37 * hash) + POSTALCODE_FIELD_NUMBER;
    hash = (53 * hash) + getPostalCode().hashCode();
    hash = (37 * hash) + DATEOFCREATION_FIELD_NUMBER;
    hash = (53 * hash) + getDateOfCreation().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static origin.protobuf.AnnouncementProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static origin.protobuf.AnnouncementProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static origin.protobuf.AnnouncementProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(origin.protobuf.AnnouncementProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnnouncementProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnnouncementProto)
      origin.protobuf.AnnouncementProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return origin.protobuf.Protobuf.internal_static_AnnouncementProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return origin.protobuf.Protobuf.internal_static_AnnouncementProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              origin.protobuf.AnnouncementProto.class, origin.protobuf.AnnouncementProto.Builder.class);
    }

    // Construct using origin.protobuf.AnnouncementProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      petOwnerEmail_ = "";

      description_ = "";

      timeStart_ = "";

      timeFinish_ = "";

      if (petBuilder_ == null) {
        pet_ = null;
      } else {
        pet_ = null;
        petBuilder_ = null;
      }
      postalCode_ = "";

      dateOfCreation_ = "";

      id_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return origin.protobuf.Protobuf.internal_static_AnnouncementProto_descriptor;
    }

    @java.lang.Override
    public origin.protobuf.AnnouncementProto getDefaultInstanceForType() {
      return origin.protobuf.AnnouncementProto.getDefaultInstance();
    }

    @java.lang.Override
    public origin.protobuf.AnnouncementProto build() {
      origin.protobuf.AnnouncementProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public origin.protobuf.AnnouncementProto buildPartial() {
      origin.protobuf.AnnouncementProto result = new origin.protobuf.AnnouncementProto(this);
      result.petOwnerEmail_ = petOwnerEmail_;
      result.description_ = description_;
      result.timeStart_ = timeStart_;
      result.timeFinish_ = timeFinish_;
      if (petBuilder_ == null) {
        result.pet_ = pet_;
      } else {
        result.pet_ = petBuilder_.build();
      }
      result.postalCode_ = postalCode_;
      result.dateOfCreation_ = dateOfCreation_;
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof origin.protobuf.AnnouncementProto) {
        return mergeFrom((origin.protobuf.AnnouncementProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(origin.protobuf.AnnouncementProto other) {
      if (other == origin.protobuf.AnnouncementProto.getDefaultInstance()) return this;
      if (!other.getPetOwnerEmail().isEmpty()) {
        petOwnerEmail_ = other.petOwnerEmail_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getTimeStart().isEmpty()) {
        timeStart_ = other.timeStart_;
        onChanged();
      }
      if (!other.getTimeFinish().isEmpty()) {
        timeFinish_ = other.timeFinish_;
        onChanged();
      }
      if (other.hasPet()) {
        mergePet(other.getPet());
      }
      if (!other.getPostalCode().isEmpty()) {
        postalCode_ = other.postalCode_;
        onChanged();
      }
      if (!other.getDateOfCreation().isEmpty()) {
        dateOfCreation_ = other.dateOfCreation_;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      origin.protobuf.AnnouncementProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (origin.protobuf.AnnouncementProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object petOwnerEmail_ = "";
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @return The petOwnerEmail.
     */
    public java.lang.String getPetOwnerEmail() {
      java.lang.Object ref = petOwnerEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        petOwnerEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @return The bytes for petOwnerEmail.
     */
    public com.google.protobuf.ByteString
        getPetOwnerEmailBytes() {
      java.lang.Object ref = petOwnerEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        petOwnerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @param value The petOwnerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setPetOwnerEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      petOwnerEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetOwnerEmail() {
      
      petOwnerEmail_ = getDefaultInstance().getPetOwnerEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @param value The bytes for petOwnerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setPetOwnerEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      petOwnerEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeStart_ = "";
    /**
     * <code>string timeStart = 3;</code>
     * @return The timeStart.
     */
    public java.lang.String getTimeStart() {
      java.lang.Object ref = timeStart_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStart_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeStart = 3;</code>
     * @return The bytes for timeStart.
     */
    public com.google.protobuf.ByteString
        getTimeStartBytes() {
      java.lang.Object ref = timeStart_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeStart = 3;</code>
     * @param value The timeStart to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStart(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeStart = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStart() {
      
      timeStart_ = getDefaultInstance().getTimeStart();
      onChanged();
      return this;
    }
    /**
     * <code>string timeStart = 3;</code>
     * @param value The bytes for timeStart to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStartBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeStart_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeFinish_ = "";
    /**
     * <code>string timeFinish = 4;</code>
     * @return The timeFinish.
     */
    public java.lang.String getTimeFinish() {
      java.lang.Object ref = timeFinish_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeFinish_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeFinish = 4;</code>
     * @return The bytes for timeFinish.
     */
    public com.google.protobuf.ByteString
        getTimeFinishBytes() {
      java.lang.Object ref = timeFinish_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeFinish_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeFinish = 4;</code>
     * @param value The timeFinish to set.
     * @return This builder for chaining.
     */
    public Builder setTimeFinish(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeFinish_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeFinish = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeFinish() {
      
      timeFinish_ = getDefaultInstance().getTimeFinish();
      onChanged();
      return this;
    }
    /**
     * <code>string timeFinish = 4;</code>
     * @param value The bytes for timeFinish to set.
     * @return This builder for chaining.
     */
    public Builder setTimeFinishBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeFinish_ = value;
      onChanged();
      return this;
    }

    private origin.protobuf.PetProto pet_;
    private com.google.protobuf.SingleFieldBuilderV3<
        origin.protobuf.PetProto, origin.protobuf.PetProto.Builder, origin.protobuf.PetProtoOrBuilder> petBuilder_;
    /**
     * <code>.PetProto pet = 5;</code>
     * @return Whether the pet field is set.
     */
    public boolean hasPet() {
      return petBuilder_ != null || pet_ != null;
    }
    /**
     * <code>.PetProto pet = 5;</code>
     * @return The pet.
     */
    public origin.protobuf.PetProto getPet() {
      if (petBuilder_ == null) {
        return pet_ == null ? origin.protobuf.PetProto.getDefaultInstance() : pet_;
      } else {
        return petBuilder_.getMessage();
      }
    }
    /**
     * <code>.PetProto pet = 5;</code>
     */
    public Builder setPet(origin.protobuf.PetProto value) {
      if (petBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pet_ = value;
        onChanged();
      } else {
        petBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.PetProto pet = 5;</code>
     */
    public Builder setPet(
        origin.protobuf.PetProto.Builder builderForValue) {
      if (petBuilder_ == null) {
        pet_ = builderForValue.build();
        onChanged();
      } else {
        petBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.PetProto pet = 5;</code>
     */
    public Builder mergePet(origin.protobuf.PetProto value) {
      if (petBuilder_ == null) {
        if (pet_ != null) {
          pet_ =
            origin.protobuf.PetProto.newBuilder(pet_).mergeFrom(value).buildPartial();
        } else {
          pet_ = value;
        }
        onChanged();
      } else {
        petBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.PetProto pet = 5;</code>
     */
    public Builder clearPet() {
      if (petBuilder_ == null) {
        pet_ = null;
        onChanged();
      } else {
        pet_ = null;
        petBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.PetProto pet = 5;</code>
     */
    public origin.protobuf.PetProto.Builder getPetBuilder() {
      
      onChanged();
      return getPetFieldBuilder().getBuilder();
    }
    /**
     * <code>.PetProto pet = 5;</code>
     */
    public origin.protobuf.PetProtoOrBuilder getPetOrBuilder() {
      if (petBuilder_ != null) {
        return petBuilder_.getMessageOrBuilder();
      } else {
        return pet_ == null ?
            origin.protobuf.PetProto.getDefaultInstance() : pet_;
      }
    }
    /**
     * <code>.PetProto pet = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        origin.protobuf.PetProto, origin.protobuf.PetProto.Builder, origin.protobuf.PetProtoOrBuilder> 
        getPetFieldBuilder() {
      if (petBuilder_ == null) {
        petBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            origin.protobuf.PetProto, origin.protobuf.PetProto.Builder, origin.protobuf.PetProtoOrBuilder>(
                getPet(),
                getParentForChildren(),
                isClean());
        pet_ = null;
      }
      return petBuilder_;
    }

    private java.lang.Object postalCode_ = "";
    /**
     * <code>string postalCode = 6;</code>
     * @return The postalCode.
     */
    public java.lang.String getPostalCode() {
      java.lang.Object ref = postalCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postalCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string postalCode = 6;</code>
     * @return The bytes for postalCode.
     */
    public com.google.protobuf.ByteString
        getPostalCodeBytes() {
      java.lang.Object ref = postalCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postalCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string postalCode = 6;</code>
     * @param value The postalCode to set.
     * @return This builder for chaining.
     */
    public Builder setPostalCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      postalCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string postalCode = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostalCode() {
      
      postalCode_ = getDefaultInstance().getPostalCode();
      onChanged();
      return this;
    }
    /**
     * <code>string postalCode = 6;</code>
     * @param value The bytes for postalCode to set.
     * @return This builder for chaining.
     */
    public Builder setPostalCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      postalCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dateOfCreation_ = "";
    /**
     * <code>string dateOfCreation = 7;</code>
     * @return The dateOfCreation.
     */
    public java.lang.String getDateOfCreation() {
      java.lang.Object ref = dateOfCreation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateOfCreation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateOfCreation = 7;</code>
     * @return The bytes for dateOfCreation.
     */
    public com.google.protobuf.ByteString
        getDateOfCreationBytes() {
      java.lang.Object ref = dateOfCreation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateOfCreation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateOfCreation = 7;</code>
     * @param value The dateOfCreation to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfCreation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateOfCreation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfCreation = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateOfCreation() {
      
      dateOfCreation_ = getDefaultInstance().getDateOfCreation();
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfCreation = 7;</code>
     * @param value The bytes for dateOfCreation to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfCreationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateOfCreation_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 8;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 8;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AnnouncementProto)
  }

  // @@protoc_insertion_point(class_scope:AnnouncementProto)
  private static final origin.protobuf.AnnouncementProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new origin.protobuf.AnnouncementProto();
  }

  public static origin.protobuf.AnnouncementProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnnouncementProto>
      PARSER = new com.google.protobuf.AbstractParser<AnnouncementProto>() {
    @java.lang.Override
    public AnnouncementProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnnouncementProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnnouncementProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnnouncementProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public origin.protobuf.AnnouncementProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

