// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface AnnouncementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Announcement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string petOwnerEmail = 1;</code>
   */
  String getPetOwnerEmail();
  /**
   * <code>string petOwnerEmail = 1;</code>
   */
  com.google.protobuf.ByteString
      getPetOwnerEmailBytes();

  /**
   * <code>string description = 2;</code>
   */
  String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.TimeInterval timeInterval = 3;</code>
   */
  boolean hasTimeInterval();
  /**
   * <code>.TimeInterval timeInterval = 3;</code>
   */
  TimeInterval getTimeInterval();
  /**
   * <code>.TimeInterval timeInterval = 3;</code>
   */
  TimeIntervalOrBuilder getTimeIntervalOrBuilder();

  /**
   * <code>.Pet pet = 4;</code>
   */
  boolean hasPet();
  /**
   * <code>.Pet pet = 4;</code>
   */
  Pet getPet();
  /**
   * <code>.Pet pet = 4;</code>
   */
  PetOrBuilder getPetOrBuilder();

  /**
   * <pre>
   * address-&gt;string postal code
   * </pre>
   *
   * <code>string postalCode = 5;</code>
   */
  String getPostalCode();
  /**
   * <pre>
   * address-&gt;string postal code
   * </pre>
   *
   * <code>string postalCode = 5;</code>
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <code>string dateOfCreation = 6;</code>
   */
  String getDateOfCreation();
  /**
   * <code>string dateOfCreation = 6;</code>
   */
  com.google.protobuf.ByteString
      getDateOfCreationBytes();
}
