// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

/**
 * Protobuf type {@code Announcements}
 */
public  final class Announcements extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Announcements)
        AnnouncementsOrBuilder {
  // Use Announcements.newBuilder() to construct.
  private Announcements(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Announcements() {
    announcements_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Announcements(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              announcements_ = new java.util.ArrayList<Announcement>();
              mutable_bitField0_ |= 0x00000001;
            }
            announcements_.add(
                input.readMessage(Announcement.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        announcements_ = java.util.Collections.unmodifiableList(announcements_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Protobuf.internal_static_Announcements_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Protobuf.internal_static_Announcements_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Announcements.class, Announcements.Builder.class);
  }

  public static final int ANNOUNCEMENTS_FIELD_NUMBER = 1;
  private java.util.List<Announcement> announcements_;
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  public java.util.List<Announcement> getAnnouncementsList() {
    return announcements_;
  }
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  public java.util.List<? extends AnnouncementOrBuilder>
      getAnnouncementsOrBuilderList() {
    return announcements_;
  }
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  public int getAnnouncementsCount() {
    return announcements_.size();
  }
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  public Announcement getAnnouncements(int index) {
    return announcements_.get(index);
  }
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  public AnnouncementOrBuilder getAnnouncementsOrBuilder(
      int index) {
    return announcements_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < announcements_.size(); i++) {
      output.writeMessage(1, announcements_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < announcements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, announcements_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Announcements)) {
      return super.equals(obj);
    }
    Announcements other = (Announcements) obj;

    boolean result = true;
    result = result && getAnnouncementsList()
        .equals(other.getAnnouncementsList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAnnouncementsCount() > 0) {
      hash = (37 * hash) + ANNOUNCEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getAnnouncementsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Announcements parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Announcements parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Announcements parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Announcements parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Announcements parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Announcements parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Announcements parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Announcements parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Announcements parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Announcements parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Announcements parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Announcements parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Announcements prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Announcements}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Announcements)
          AnnouncementsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.internal_static_Announcements_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.internal_static_Announcements_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Announcements.class, Announcements.Builder.class);
    }

    // Construct using origin.protobuf.Announcements.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnnouncementsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (announcementsBuilder_ == null) {
        announcements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        announcementsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Protobuf.internal_static_Announcements_descriptor;
    }

    public Announcements getDefaultInstanceForType() {
      return Announcements.getDefaultInstance();
    }

    public Announcements build() {
      Announcements result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Announcements buildPartial() {
      Announcements result = new Announcements(this);
      int from_bitField0_ = bitField0_;
      if (announcementsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          announcements_ = java.util.Collections.unmodifiableList(announcements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.announcements_ = announcements_;
      } else {
        result.announcements_ = announcementsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Announcements) {
        return mergeFrom((Announcements)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Announcements other) {
      if (other == Announcements.getDefaultInstance()) return this;
      if (announcementsBuilder_ == null) {
        if (!other.announcements_.isEmpty()) {
          if (announcements_.isEmpty()) {
            announcements_ = other.announcements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnnouncementsIsMutable();
            announcements_.addAll(other.announcements_);
          }
          onChanged();
        }
      } else {
        if (!other.announcements_.isEmpty()) {
          if (announcementsBuilder_.isEmpty()) {
            announcementsBuilder_.dispose();
            announcementsBuilder_ = null;
            announcements_ = other.announcements_;
            bitField0_ = (bitField0_ & ~0x00000001);
            announcementsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnnouncementsFieldBuilder() : null;
          } else {
            announcementsBuilder_.addAllMessages(other.announcements_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Announcements parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Announcements) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Announcement> announcements_ =
      java.util.Collections.emptyList();
    private void ensureAnnouncementsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        announcements_ = new java.util.ArrayList<Announcement>(announcements_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Announcement, Announcement.Builder, AnnouncementOrBuilder> announcementsBuilder_;

    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public java.util.List<Announcement> getAnnouncementsList() {
      if (announcementsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(announcements_);
      } else {
        return announcementsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public int getAnnouncementsCount() {
      if (announcementsBuilder_ == null) {
        return announcements_.size();
      } else {
        return announcementsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Announcement getAnnouncements(int index) {
      if (announcementsBuilder_ == null) {
        return announcements_.get(index);
      } else {
        return announcementsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder setAnnouncements(
        int index, Announcement value) {
      if (announcementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnouncementsIsMutable();
        announcements_.set(index, value);
        onChanged();
      } else {
        announcementsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder setAnnouncements(
        int index, Announcement.Builder builderForValue) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        announcements_.set(index, builderForValue.build());
        onChanged();
      } else {
        announcementsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder addAnnouncements(Announcement value) {
      if (announcementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnouncementsIsMutable();
        announcements_.add(value);
        onChanged();
      } else {
        announcementsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder addAnnouncements(
        int index, Announcement value) {
      if (announcementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnouncementsIsMutable();
        announcements_.add(index, value);
        onChanged();
      } else {
        announcementsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder addAnnouncements(
        Announcement.Builder builderForValue) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        announcements_.add(builderForValue.build());
        onChanged();
      } else {
        announcementsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder addAnnouncements(
        int index, Announcement.Builder builderForValue) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        announcements_.add(index, builderForValue.build());
        onChanged();
      } else {
        announcementsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder addAllAnnouncements(
        Iterable<? extends Announcement> values) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, announcements_);
        onChanged();
      } else {
        announcementsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder clearAnnouncements() {
      if (announcementsBuilder_ == null) {
        announcements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        announcementsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Builder removeAnnouncements(int index) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        announcements_.remove(index);
        onChanged();
      } else {
        announcementsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Announcement.Builder getAnnouncementsBuilder(
        int index) {
      return getAnnouncementsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public AnnouncementOrBuilder getAnnouncementsOrBuilder(
        int index) {
      if (announcementsBuilder_ == null) {
        return announcements_.get(index);  } else {
        return announcementsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public java.util.List<? extends AnnouncementOrBuilder>
         getAnnouncementsOrBuilderList() {
      if (announcementsBuilder_ != null) {
        return announcementsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(announcements_);
      }
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Announcement.Builder addAnnouncementsBuilder() {
      return getAnnouncementsFieldBuilder().addBuilder(
          Announcement.getDefaultInstance());
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public Announcement.Builder addAnnouncementsBuilder(
        int index) {
      return getAnnouncementsFieldBuilder().addBuilder(
          index, Announcement.getDefaultInstance());
    }
    /**
     * <code>repeated .Announcement announcements = 1;</code>
     */
    public java.util.List<Announcement.Builder>
         getAnnouncementsBuilderList() {
      return getAnnouncementsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            Announcement, Announcement.Builder, AnnouncementOrBuilder>
        getAnnouncementsFieldBuilder() {
      if (announcementsBuilder_ == null) {
        announcementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                Announcement, Announcement.Builder, AnnouncementOrBuilder>(
                announcements_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        announcements_ = null;
      }
      return announcementsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Announcements)
  }

  // @@protoc_insertion_point(class_scope:Announcements)
  private static final Announcements DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Announcements();
  }

  public static Announcements getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Announcements>
      PARSER = new com.google.protobuf.AbstractParser<Announcements>() {
    public Announcements parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Announcements(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Announcements> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Announcements> getParserForType() {
    return PARSER;
  }

  public Announcements getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

