// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface AnnouncementsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Announcements)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  java.util.List<Announcement>
      getAnnouncementsList();
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  Announcement getAnnouncements(int index);
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  int getAnnouncementsCount();
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  java.util.List<? extends AnnouncementOrBuilder>
      getAnnouncementsOrBuilderList();
  /**
   * <code>repeated .Announcement announcements = 1;</code>
   */
  AnnouncementOrBuilder getAnnouncementsOrBuilder(
      int index);
}
