// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface LoginUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * username-&gt;email
   * </pre>
   *
   * <code>string email = 1;</code>
   */
  String getEmail();
  /**
   * <pre>
   * username-&gt;email
   * </pre>
   *
   * <code>string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
