// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public final class Protobuf {
  private Protobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PetOwner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PetOwner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Announcement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Announcement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Announcements_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Announcements_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeInterval_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimeInterval_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Void_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Void_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016protobuf.proto\032\037google/protobuf/timest" +
      "amp.proto\"Y\n\010PetOwner\022\020\n\010username\030\001 \001(\t\022" +
      "\020\n\010password\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\r\n\005phone\030" +
      "\004 \001(\t\022\r\n\005email\030\005 \001(\t\",\n\tLoginUser\022\r\n\005ema" +
      "il\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\236\001\n\014Announcem" +
      "ent\022\025\n\rpetOwnerEmail\030\001 \001(\t\022\023\n\013descriptio" +
      "n\030\002 \001(\t\022#\n\014timeInterval\030\003 \001(\0132\r.TimeInte" +
      "rval\022\021\n\003pet\030\004 \001(\0132\004.Pet\022\022\n\npostalCode\030\005 " +
      "\001(\t\022\026\n\016dateOfCreation\030\006 \001(\t\"5\n\rAnnouncem" +
      "ents\022$\n\rannouncements\030\001 \003(\0132\r.Announceme",
      "nt\"f\n\003Pet\022\017\n\007petName\030\001 \001(\t\022\017\n\007petType\030\002 " +
      "\001(\t\022\016\n\006weight\030\003 \001(\005\022\024\n\014isVaccinated\030\004 \001(" +
      "\010\022\027\n\017dietDescription\030\005 \001(\t\"5\n\014TimeInterv" +
      "al\022\021\n\tstartDate\030\001 \001(\t\022\022\n\nfinishDate\030\002 \001(" +
      "\t\"\035\n\013SearchField\022\016\n\006search\030\001 \001(\t\"\006\n\004Void" +
      "2\212\001\n\017PetOwnerService\022&\n\016CreatePetOwner\022\t" +
      ".PetOwner\032\t.PetOwner\022&\n\rLoginPetOwner\022\n." +
      "LoginUser\032\t.PetOwner\022\'\n\014FindPetOwner\022\014.S" +
      "earchField\032\t.PetOwner2\324\001\n\023AnnouncementSe" +
      "rvice\0222\n\022CreateAnnouncement\022\r.Announceme",
      "nt\032\r.Announcement\0221\n\021FindAnnouncements\022\014" +
      ".SearchField\032\016.Announcements\022*\n\022UpdateAn" +
      "nouncement\022\r.Announcement\032\005.Void\022*\n\022Dele" +
      "teAnnouncement\022\r.Announcement\032\005.VoidB\023\n\017" +
      "origin.protobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_PetOwner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PetOwner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PetOwner_descriptor,
        new String[] { "Username", "Password", "Age", "Phone", "Email", });
    internal_static_LoginUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginUser_descriptor,
        new String[] { "Email", "Password", });
    internal_static_Announcement_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Announcement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Announcement_descriptor,
        new String[] { "PetOwnerEmail", "Description", "TimeInterval", "Pet", "PostalCode", "DateOfCreation", });
    internal_static_Announcements_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Announcements_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Announcements_descriptor,
        new String[] { "Announcements", });
    internal_static_Pet_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Pet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pet_descriptor,
        new String[] { "PetName", "PetType", "Weight", "IsVaccinated", "DietDescription", });
    internal_static_TimeInterval_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_TimeInterval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimeInterval_descriptor,
        new String[] { "StartDate", "FinishDate", });
    internal_static_SearchField_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SearchField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchField_descriptor,
        new String[] { "Search", });
    internal_static_Void_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Void_descriptor,
        new String[] { });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
