// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface SearchFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string search = 1;</code>
   */
  String getSearch();
  /**
   * <code>string search = 1;</code>
   */
  com.google.protobuf.ByteString
      getSearchBytes();
}
