// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface TimeIntervalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TimeInterval)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startDate = 1;</code>
   */
  String getStartDate();
  /**
   * <code>string startDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string finishDate = 2;</code>
   */
  String getFinishDate();
  /**
   * <code>string finishDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getFinishDateBytes();
}
