// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Void)
    com.google.protobuf.MessageOrBuilder {
}
