// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobuf;

/**
 * Protobuf type {@code AnnouncementsProto}
 */
public final class AnnouncementsProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AnnouncementsProto)
    AnnouncementsProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnnouncementsProto.newBuilder() to construct.
  private AnnouncementsProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnnouncementsProto() {
    announcements_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnnouncementsProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnnouncementsProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              announcements_ = new java.util.ArrayList<origin.protobuf.AnnouncementProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            announcements_.add(
                input.readMessage(origin.protobuf.AnnouncementProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        announcements_ = java.util.Collections.unmodifiableList(announcements_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return origin.protobuf.Protobuf.internal_static_AnnouncementsProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return origin.protobuf.Protobuf.internal_static_AnnouncementsProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            origin.protobuf.AnnouncementsProto.class, origin.protobuf.AnnouncementsProto.Builder.class);
  }

  public static final int ANNOUNCEMENTS_FIELD_NUMBER = 1;
  private java.util.List<origin.protobuf.AnnouncementProto> announcements_;
  /**
   * <code>repeated .AnnouncementProto announcements = 1;</code>
   */
  @java.lang.Override
  public java.util.List<origin.protobuf.AnnouncementProto> getAnnouncementsList() {
    return announcements_;
  }
  /**
   * <code>repeated .AnnouncementProto announcements = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends origin.protobuf.AnnouncementProtoOrBuilder> 
      getAnnouncementsOrBuilderList() {
    return announcements_;
  }
  /**
   * <code>repeated .AnnouncementProto announcements = 1;</code>
   */
  @java.lang.Override
  public int getAnnouncementsCount() {
    return announcements_.size();
  }
  /**
   * <code>repeated .AnnouncementProto announcements = 1;</code>
   */
  @java.lang.Override
  public origin.protobuf.AnnouncementProto getAnnouncements(int index) {
    return announcements_.get(index);
  }
  /**
   * <code>repeated .AnnouncementProto announcements = 1;</code>
   */
  @java.lang.Override
  public origin.protobuf.AnnouncementProtoOrBuilder getAnnouncementsOrBuilder(
      int index) {
    return announcements_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < announcements_.size(); i++) {
      output.writeMessage(1, announcements_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < announcements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, announcements_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof origin.protobuf.AnnouncementsProto)) {
      return super.equals(obj);
    }
    origin.protobuf.AnnouncementsProto other = (origin.protobuf.AnnouncementsProto) obj;

    if (!getAnnouncementsList()
        .equals(other.getAnnouncementsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAnnouncementsCount() > 0) {
      hash = (37 * hash) + ANNOUNCEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getAnnouncementsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static origin.protobuf.AnnouncementsProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementsProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static origin.protobuf.AnnouncementsProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static origin.protobuf.AnnouncementsProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(origin.protobuf.AnnouncementsProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnnouncementsProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnnouncementsProto)
      origin.protobuf.AnnouncementsProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return origin.protobuf.Protobuf.internal_static_AnnouncementsProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return origin.protobuf.Protobuf.internal_static_AnnouncementsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              origin.protobuf.AnnouncementsProto.class, origin.protobuf.AnnouncementsProto.Builder.class);
    }

    // Construct using origin.protobuf.AnnouncementsProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnnouncementsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (announcementsBuilder_ == null) {
        announcements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        announcementsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return origin.protobuf.Protobuf.internal_static_AnnouncementsProto_descriptor;
    }

    @java.lang.Override
    public origin.protobuf.AnnouncementsProto getDefaultInstanceForType() {
      return origin.protobuf.AnnouncementsProto.getDefaultInstance();
    }

    @java.lang.Override
    public origin.protobuf.AnnouncementsProto build() {
      origin.protobuf.AnnouncementsProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public origin.protobuf.AnnouncementsProto buildPartial() {
      origin.protobuf.AnnouncementsProto result = new origin.protobuf.AnnouncementsProto(this);
      int from_bitField0_ = bitField0_;
      if (announcementsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          announcements_ = java.util.Collections.unmodifiableList(announcements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.announcements_ = announcements_;
      } else {
        result.announcements_ = announcementsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof origin.protobuf.AnnouncementsProto) {
        return mergeFrom((origin.protobuf.AnnouncementsProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(origin.protobuf.AnnouncementsProto other) {
      if (other == origin.protobuf.AnnouncementsProto.getDefaultInstance()) return this;
      if (announcementsBuilder_ == null) {
        if (!other.announcements_.isEmpty()) {
          if (announcements_.isEmpty()) {
            announcements_ = other.announcements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnnouncementsIsMutable();
            announcements_.addAll(other.announcements_);
          }
          onChanged();
        }
      } else {
        if (!other.announcements_.isEmpty()) {
          if (announcementsBuilder_.isEmpty()) {
            announcementsBuilder_.dispose();
            announcementsBuilder_ = null;
            announcements_ = other.announcements_;
            bitField0_ = (bitField0_ & ~0x00000001);
            announcementsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnnouncementsFieldBuilder() : null;
          } else {
            announcementsBuilder_.addAllMessages(other.announcements_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      origin.protobuf.AnnouncementsProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (origin.protobuf.AnnouncementsProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<origin.protobuf.AnnouncementProto> announcements_ =
      java.util.Collections.emptyList();
    private void ensureAnnouncementsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        announcements_ = new java.util.ArrayList<origin.protobuf.AnnouncementProto>(announcements_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        origin.protobuf.AnnouncementProto, origin.protobuf.AnnouncementProto.Builder, origin.protobuf.AnnouncementProtoOrBuilder> announcementsBuilder_;

    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public java.util.List<origin.protobuf.AnnouncementProto> getAnnouncementsList() {
      if (announcementsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(announcements_);
      } else {
        return announcementsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public int getAnnouncementsCount() {
      if (announcementsBuilder_ == null) {
        return announcements_.size();
      } else {
        return announcementsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public origin.protobuf.AnnouncementProto getAnnouncements(int index) {
      if (announcementsBuilder_ == null) {
        return announcements_.get(index);
      } else {
        return announcementsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder setAnnouncements(
        int index, origin.protobuf.AnnouncementProto value) {
      if (announcementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnouncementsIsMutable();
        announcements_.set(index, value);
        onChanged();
      } else {
        announcementsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder setAnnouncements(
        int index, origin.protobuf.AnnouncementProto.Builder builderForValue) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        announcements_.set(index, builderForValue.build());
        onChanged();
      } else {
        announcementsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder addAnnouncements(origin.protobuf.AnnouncementProto value) {
      if (announcementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnouncementsIsMutable();
        announcements_.add(value);
        onChanged();
      } else {
        announcementsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder addAnnouncements(
        int index, origin.protobuf.AnnouncementProto value) {
      if (announcementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnouncementsIsMutable();
        announcements_.add(index, value);
        onChanged();
      } else {
        announcementsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder addAnnouncements(
        origin.protobuf.AnnouncementProto.Builder builderForValue) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        announcements_.add(builderForValue.build());
        onChanged();
      } else {
        announcementsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder addAnnouncements(
        int index, origin.protobuf.AnnouncementProto.Builder builderForValue) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        announcements_.add(index, builderForValue.build());
        onChanged();
      } else {
        announcementsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder addAllAnnouncements(
        java.lang.Iterable<? extends origin.protobuf.AnnouncementProto> values) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, announcements_);
        onChanged();
      } else {
        announcementsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder clearAnnouncements() {
      if (announcementsBuilder_ == null) {
        announcements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        announcementsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public Builder removeAnnouncements(int index) {
      if (announcementsBuilder_ == null) {
        ensureAnnouncementsIsMutable();
        announcements_.remove(index);
        onChanged();
      } else {
        announcementsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public origin.protobuf.AnnouncementProto.Builder getAnnouncementsBuilder(
        int index) {
      return getAnnouncementsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public origin.protobuf.AnnouncementProtoOrBuilder getAnnouncementsOrBuilder(
        int index) {
      if (announcementsBuilder_ == null) {
        return announcements_.get(index);  } else {
        return announcementsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public java.util.List<? extends origin.protobuf.AnnouncementProtoOrBuilder> 
         getAnnouncementsOrBuilderList() {
      if (announcementsBuilder_ != null) {
        return announcementsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(announcements_);
      }
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public origin.protobuf.AnnouncementProto.Builder addAnnouncementsBuilder() {
      return getAnnouncementsFieldBuilder().addBuilder(
          origin.protobuf.AnnouncementProto.getDefaultInstance());
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public origin.protobuf.AnnouncementProto.Builder addAnnouncementsBuilder(
        int index) {
      return getAnnouncementsFieldBuilder().addBuilder(
          index, origin.protobuf.AnnouncementProto.getDefaultInstance());
    }
    /**
     * <code>repeated .AnnouncementProto announcements = 1;</code>
     */
    public java.util.List<origin.protobuf.AnnouncementProto.Builder> 
         getAnnouncementsBuilderList() {
      return getAnnouncementsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        origin.protobuf.AnnouncementProto, origin.protobuf.AnnouncementProto.Builder, origin.protobuf.AnnouncementProtoOrBuilder> 
        getAnnouncementsFieldBuilder() {
      if (announcementsBuilder_ == null) {
        announcementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            origin.protobuf.AnnouncementProto, origin.protobuf.AnnouncementProto.Builder, origin.protobuf.AnnouncementProtoOrBuilder>(
                announcements_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        announcements_ = null;
      }
      return announcementsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AnnouncementsProto)
  }

  // @@protoc_insertion_point(class_scope:AnnouncementsProto)
  private static final origin.protobuf.AnnouncementsProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new origin.protobuf.AnnouncementsProto();
  }

  public static origin.protobuf.AnnouncementsProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnnouncementsProto>
      PARSER = new com.google.protobuf.AbstractParser<AnnouncementsProto>() {
    @java.lang.Override
    public AnnouncementsProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnnouncementsProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnnouncementsProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnnouncementsProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public origin.protobuf.AnnouncementsProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

