// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobuf;

public interface AnnouncementProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnnouncementProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string petOwnerEmail = 1;</code>
   * @return The petOwnerEmail.
   */
  java.lang.String getPetOwnerEmail();
  /**
   * <code>string petOwnerEmail = 1;</code>
   * @return The bytes for petOwnerEmail.
   */
  com.google.protobuf.ByteString
      getPetOwnerEmailBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string timeStart = 3;</code>
   * @return The timeStart.
   */
  java.lang.String getTimeStart();
  /**
   * <code>string timeStart = 3;</code>
   * @return The bytes for timeStart.
   */
  com.google.protobuf.ByteString
      getTimeStartBytes();

  /**
   * <code>string timeFinish = 4;</code>
   * @return The timeFinish.
   */
  java.lang.String getTimeFinish();
  /**
   * <code>string timeFinish = 4;</code>
   * @return The bytes for timeFinish.
   */
  com.google.protobuf.ByteString
      getTimeFinishBytes();

  /**
   * <code>.PetProto pet = 5;</code>
   * @return Whether the pet field is set.
   */
  boolean hasPet();
  /**
   * <code>.PetProto pet = 5;</code>
   * @return The pet.
   */
  origin.protobuf.PetProto getPet();
  /**
   * <code>.PetProto pet = 5;</code>
   */
  origin.protobuf.PetProtoOrBuilder getPetOrBuilder();

  /**
   * <code>string postalCode = 6;</code>
   * @return The postalCode.
   */
  java.lang.String getPostalCode();
  /**
   * <code>string postalCode = 6;</code>
   * @return The bytes for postalCode.
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <code>string dateOfCreation = 7;</code>
   * @return The dateOfCreation.
   */
  java.lang.String getDateOfCreation();
  /**
   * <code>string dateOfCreation = 7;</code>
   * @return The bytes for dateOfCreation.
   */
  com.google.protobuf.ByteString
      getDateOfCreationBytes();

  /**
   * <code>int32 id = 8;</code>
   * @return The id.
   */
  int getId();
}
