// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobuf;

/**
 * Protobuf type {@code PetProto}
 */
public final class PetProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PetProto)
    PetProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PetProto.newBuilder() to construct.
  private PetProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PetProto() {
    petName_ = "";
    petType_ = "";
    description_ = "";
    ownerEmail_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PetProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PetProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            petName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            petType_ = s;
            break;
          }
          case 24: {

            weight_ = input.readInt32();
            break;
          }
          case 32: {

            isVaccinated_ = input.readBool();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 48: {

            id_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            ownerEmail_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return origin.protobuf.Protobuf.internal_static_PetProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return origin.protobuf.Protobuf.internal_static_PetProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            origin.protobuf.PetProto.class, origin.protobuf.PetProto.Builder.class);
  }

  public static final int PETNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object petName_;
  /**
   * <code>string petName = 1;</code>
   * @return The petName.
   */
  @java.lang.Override
  public java.lang.String getPetName() {
    java.lang.Object ref = petName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      petName_ = s;
      return s;
    }
  }
  /**
   * <code>string petName = 1;</code>
   * @return The bytes for petName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPetNameBytes() {
    java.lang.Object ref = petName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      petName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PETTYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object petType_;
  /**
   * <code>string petType = 2;</code>
   * @return The petType.
   */
  @java.lang.Override
  public java.lang.String getPetType() {
    java.lang.Object ref = petType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      petType_ = s;
      return s;
    }
  }
  /**
   * <code>string petType = 2;</code>
   * @return The bytes for petType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPetTypeBytes() {
    java.lang.Object ref = petType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      petType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEIGHT_FIELD_NUMBER = 3;
  private int weight_;
  /**
   * <code>int32 weight = 3;</code>
   * @return The weight.
   */
  @java.lang.Override
  public int getWeight() {
    return weight_;
  }

  public static final int ISVACCINATED_FIELD_NUMBER = 4;
  private boolean isVaccinated_;
  /**
   * <code>bool isVaccinated = 4;</code>
   * @return The isVaccinated.
   */
  @java.lang.Override
  public boolean getIsVaccinated() {
    return isVaccinated_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 5;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 6;
  private int id_;
  /**
   * <code>int32 id = 6;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int OWNEREMAIL_FIELD_NUMBER = 7;
  private volatile java.lang.Object ownerEmail_;
  /**
   * <code>string ownerEmail = 7;</code>
   * @return The ownerEmail.
   */
  @java.lang.Override
  public java.lang.String getOwnerEmail() {
    java.lang.Object ref = ownerEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string ownerEmail = 7;</code>
   * @return The bytes for ownerEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerEmailBytes() {
    java.lang.Object ref = ownerEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, petName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, petType_);
    }
    if (weight_ != 0) {
      output.writeInt32(3, weight_);
    }
    if (isVaccinated_ != false) {
      output.writeBool(4, isVaccinated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
    }
    if (id_ != 0) {
      output.writeInt32(6, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ownerEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ownerEmail_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, petName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, petType_);
    }
    if (weight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, weight_);
    }
    if (isVaccinated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isVaccinated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ownerEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ownerEmail_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof origin.protobuf.PetProto)) {
      return super.equals(obj);
    }
    origin.protobuf.PetProto other = (origin.protobuf.PetProto) obj;

    if (!getPetName()
        .equals(other.getPetName())) return false;
    if (!getPetType()
        .equals(other.getPetType())) return false;
    if (getWeight()
        != other.getWeight()) return false;
    if (getIsVaccinated()
        != other.getIsVaccinated()) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getId()
        != other.getId()) return false;
    if (!getOwnerEmail()
        .equals(other.getOwnerEmail())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PETNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPetName().hashCode();
    hash = (37 * hash) + PETTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPetType().hashCode();
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getWeight();
    hash = (37 * hash) + ISVACCINATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsVaccinated());
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + OWNEREMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerEmail().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static origin.protobuf.PetProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.PetProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.PetProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.PetProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.PetProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.PetProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.PetProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static origin.protobuf.PetProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static origin.protobuf.PetProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static origin.protobuf.PetProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static origin.protobuf.PetProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static origin.protobuf.PetProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(origin.protobuf.PetProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PetProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PetProto)
      origin.protobuf.PetProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return origin.protobuf.Protobuf.internal_static_PetProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return origin.protobuf.Protobuf.internal_static_PetProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              origin.protobuf.PetProto.class, origin.protobuf.PetProto.Builder.class);
    }

    // Construct using origin.protobuf.PetProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      petName_ = "";

      petType_ = "";

      weight_ = 0;

      isVaccinated_ = false;

      description_ = "";

      id_ = 0;

      ownerEmail_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return origin.protobuf.Protobuf.internal_static_PetProto_descriptor;
    }

    @java.lang.Override
    public origin.protobuf.PetProto getDefaultInstanceForType() {
      return origin.protobuf.PetProto.getDefaultInstance();
    }

    @java.lang.Override
    public origin.protobuf.PetProto build() {
      origin.protobuf.PetProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public origin.protobuf.PetProto buildPartial() {
      origin.protobuf.PetProto result = new origin.protobuf.PetProto(this);
      result.petName_ = petName_;
      result.petType_ = petType_;
      result.weight_ = weight_;
      result.isVaccinated_ = isVaccinated_;
      result.description_ = description_;
      result.id_ = id_;
      result.ownerEmail_ = ownerEmail_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof origin.protobuf.PetProto) {
        return mergeFrom((origin.protobuf.PetProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(origin.protobuf.PetProto other) {
      if (other == origin.protobuf.PetProto.getDefaultInstance()) return this;
      if (!other.getPetName().isEmpty()) {
        petName_ = other.petName_;
        onChanged();
      }
      if (!other.getPetType().isEmpty()) {
        petType_ = other.petType_;
        onChanged();
      }
      if (other.getWeight() != 0) {
        setWeight(other.getWeight());
      }
      if (other.getIsVaccinated() != false) {
        setIsVaccinated(other.getIsVaccinated());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getOwnerEmail().isEmpty()) {
        ownerEmail_ = other.ownerEmail_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      origin.protobuf.PetProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (origin.protobuf.PetProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object petName_ = "";
    /**
     * <code>string petName = 1;</code>
     * @return The petName.
     */
    public java.lang.String getPetName() {
      java.lang.Object ref = petName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        petName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string petName = 1;</code>
     * @return The bytes for petName.
     */
    public com.google.protobuf.ByteString
        getPetNameBytes() {
      java.lang.Object ref = petName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        petName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string petName = 1;</code>
     * @param value The petName to set.
     * @return This builder for chaining.
     */
    public Builder setPetName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      petName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string petName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetName() {
      
      petName_ = getDefaultInstance().getPetName();
      onChanged();
      return this;
    }
    /**
     * <code>string petName = 1;</code>
     * @param value The bytes for petName to set.
     * @return This builder for chaining.
     */
    public Builder setPetNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      petName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object petType_ = "";
    /**
     * <code>string petType = 2;</code>
     * @return The petType.
     */
    public java.lang.String getPetType() {
      java.lang.Object ref = petType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        petType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string petType = 2;</code>
     * @return The bytes for petType.
     */
    public com.google.protobuf.ByteString
        getPetTypeBytes() {
      java.lang.Object ref = petType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        petType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string petType = 2;</code>
     * @param value The petType to set.
     * @return This builder for chaining.
     */
    public Builder setPetType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      petType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string petType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetType() {
      
      petType_ = getDefaultInstance().getPetType();
      onChanged();
      return this;
    }
    /**
     * <code>string petType = 2;</code>
     * @param value The bytes for petType to set.
     * @return This builder for chaining.
     */
    public Builder setPetTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      petType_ = value;
      onChanged();
      return this;
    }

    private int weight_ ;
    /**
     * <code>int32 weight = 3;</code>
     * @return The weight.
     */
    @java.lang.Override
    public int getWeight() {
      return weight_;
    }
    /**
     * <code>int32 weight = 3;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(int value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 weight = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0;
      onChanged();
      return this;
    }

    private boolean isVaccinated_ ;
    /**
     * <code>bool isVaccinated = 4;</code>
     * @return The isVaccinated.
     */
    @java.lang.Override
    public boolean getIsVaccinated() {
      return isVaccinated_;
    }
    /**
     * <code>bool isVaccinated = 4;</code>
     * @param value The isVaccinated to set.
     * @return This builder for chaining.
     */
    public Builder setIsVaccinated(boolean value) {
      
      isVaccinated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isVaccinated = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsVaccinated() {
      
      isVaccinated_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 5;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 5;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 5;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 5;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 6;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 6;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ownerEmail_ = "";
    /**
     * <code>string ownerEmail = 7;</code>
     * @return The ownerEmail.
     */
    public java.lang.String getOwnerEmail() {
      java.lang.Object ref = ownerEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ownerEmail = 7;</code>
     * @return The bytes for ownerEmail.
     */
    public com.google.protobuf.ByteString
        getOwnerEmailBytes() {
      java.lang.Object ref = ownerEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ownerEmail = 7;</code>
     * @param value The ownerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ownerEmail = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerEmail() {
      
      ownerEmail_ = getDefaultInstance().getOwnerEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string ownerEmail = 7;</code>
     * @param value The bytes for ownerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerEmail_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PetProto)
  }

  // @@protoc_insertion_point(class_scope:PetProto)
  private static final origin.protobuf.PetProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new origin.protobuf.PetProto();
  }

  public static origin.protobuf.PetProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PetProto>
      PARSER = new com.google.protobuf.AbstractParser<PetProto>() {
    @java.lang.Override
    public PetProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PetProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PetProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PetProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public origin.protobuf.PetProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

