// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobuf;

public interface PetProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PetProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string petName = 1;</code>
   * @return The petName.
   */
  java.lang.String getPetName();
  /**
   * <code>string petName = 1;</code>
   * @return The bytes for petName.
   */
  com.google.protobuf.ByteString
      getPetNameBytes();

  /**
   * <code>string petType = 2;</code>
   * @return The petType.
   */
  java.lang.String getPetType();
  /**
   * <code>string petType = 2;</code>
   * @return The bytes for petType.
   */
  com.google.protobuf.ByteString
      getPetTypeBytes();

  /**
   * <code>int32 weight = 3;</code>
   * @return The weight.
   */
  int getWeight();

  /**
   * <code>bool isVaccinated = 4;</code>
   * @return The isVaccinated.
   */
  boolean getIsVaccinated();

  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 id = 6;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string ownerEmail = 7;</code>
   * @return The ownerEmail.
   */
  java.lang.String getOwnerEmail();
  /**
   * <code>string ownerEmail = 7;</code>
   * @return The bytes for ownerEmail.
   */
  com.google.protobuf.ByteString
      getOwnerEmailBytes();
}
