// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobuf;

public final class Protobuf {
  private Protobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UsersProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UsersProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindUserProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindUserProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchUsersProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchUsersProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginUserProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginUserProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnnouncementProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnnouncementProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnnouncementsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnnouncementsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindAnnouncementProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindAnnouncementProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchAnnouncementProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchAnnouncementProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PetProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PetProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Void_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Void_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protobuf.proto\"h\n\tUserProto\022\r\n\005email\030\001" +
      " \001(\t\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 \001(\t" +
      "\022\013\n\003age\030\004 \001(\005\022\r\n\005phone\030\005 \001(\t\022\014\n\004type\030\006 \001" +
      "(\t\"\'\n\nUsersProto\022\031\n\005users\030\001 \003(\0132\n.UserPr" +
      "oto\"\036\n\rFindUserProto\022\r\n\005email\030\001 \001(\t\" \n\020S" +
      "earchUsersProto\022\014\n\004type\030\001 \001(\t\"1\n\016LoginUs" +
      "erProto\022\r\n\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t" +
      "\"\266\001\n\021AnnouncementProto\022\025\n\rpetOwnerEmail\030" +
      "\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\021\n\ttimeStart\030" +
      "\003 \001(\t\022\022\n\ntimeFinish\030\004 \001(\t\022\026\n\003pet\030\005 \001(\0132\t" +
      ".PetProto\022\022\n\npostalCode\030\006 \001(\t\022\026\n\016dateOfC" +
      "reation\030\007 \001(\t\022\n\n\002id\030\010 \001(\005\"?\n\022Announcemen" +
      "tsProto\022)\n\rannouncements\030\001 \003(\0132\022.Announc" +
      "ementProto\"#\n\025FindAnnouncementProto\022\n\n\002i" +
      "d\030\001 \001(\005\"\250\001\n\027SearchAnnouncementProto\022\025\n\rp" +
      "etOwnerEmail\030\001 \001(\t\022\021\n\ttimeStart\030\002 \001(\t\022\022\n" +
      "\ntimeFinish\030\003 \001(\t\022\022\n\npostalCode\030\004 \001(\t\022\017\n" +
      "\007petType\030\005 \001(\t\022\021\n\tpetWeight\030\006 \001(\005\022\027\n\017pet" +
      "IsVaccinated\030\007 \001(\010\"\207\001\n\010PetProto\022\017\n\007petNa" +
      "me\030\001 \001(\t\022\017\n\007petType\030\002 \001(\t\022\016\n\006weight\030\003 \001(" +
      "\005\022\024\n\014isVaccinated\030\004 \001(\010\022\023\n\013description\030\005" +
      " \001(\t\022\n\n\002id\030\006 \001(\005\022\022\n\nownerEmail\030\007 \001(\t\"(\n\016" +
      "ResponseStatus\022\026\n\016responseStatus\030\001 \001(\t\"\006" +
      "\n\004Void2\204\002\n\013UserService\022$\n\nCreateUser\022\n.U" +
      "serProto\032\n.UserProto\022$\n\005LogIn\022\017.LoginUse" +
      "rProto\032\n.UserProto\022&\n\010FindUser\022\016.FindUse" +
      "rProto\032\n.UserProto\022,\n\nSearchUser\022\021.Searc" +
      "hUsersProto\032\013.UsersProto\022$\n\nUpdateUser\022\n" +
      ".UserProto\032\n.UserProto\022-\n\nDeleteUser\022\016.F" +
      "indUserProto\032\017.ResponseStatus2\323\002\n\023Announ" +
      "cementService\022<\n\022CreateAnnouncement\022\022.An" +
      "nouncementProto\032\022.AnnouncementProto\022B\n\021F" +
      "indAnnouncements\022\030.SearchAnnouncementPro" +
      "to\032\023.AnnouncementsProto\022=\n\017GetAnnounceme" +
      "nt\022\026.FindAnnouncementProto\032\022.Announcemen" +
      "tProto\022<\n\022UpdateAnnouncement\022\022.Announcem" +
      "entProto\032\022.AnnouncementProto\022=\n\022DeleteAn" +
      "nouncement\022\026.FindAnnouncementProto\032\017.Res" +
      "ponseStatusB\023\n\017origin.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserProto_descriptor,
        new java.lang.String[] { "Email", "Username", "Password", "Age", "Phone", "Type", });
    internal_static_UsersProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UsersProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UsersProto_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_FindUserProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FindUserProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindUserProto_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_SearchUsersProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SearchUsersProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchUsersProto_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_LoginUserProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LoginUserProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginUserProto_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_AnnouncementProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AnnouncementProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnnouncementProto_descriptor,
        new java.lang.String[] { "PetOwnerEmail", "Description", "TimeStart", "TimeFinish", "Pet", "PostalCode", "DateOfCreation", "Id", });
    internal_static_AnnouncementsProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AnnouncementsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnnouncementsProto_descriptor,
        new java.lang.String[] { "Announcements", });
    internal_static_FindAnnouncementProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_FindAnnouncementProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindAnnouncementProto_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_SearchAnnouncementProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_SearchAnnouncementProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchAnnouncementProto_descriptor,
        new java.lang.String[] { "PetOwnerEmail", "TimeStart", "TimeFinish", "PostalCode", "PetType", "PetWeight", "PetIsVaccinated", });
    internal_static_PetProto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_PetProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PetProto_descriptor,
        new java.lang.String[] { "PetName", "PetType", "Weight", "IsVaccinated", "Description", "Id", "OwnerEmail", });
    internal_static_ResponseStatus_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ResponseStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseStatus_descriptor,
        new java.lang.String[] { "ResponseStatus", });
    internal_static_Void_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Void_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
