// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobuf;

public interface SearchAnnouncementProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchAnnouncementProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string petOwnerEmail = 1;</code>
   * @return The petOwnerEmail.
   */
  java.lang.String getPetOwnerEmail();
  /**
   * <code>string petOwnerEmail = 1;</code>
   * @return The bytes for petOwnerEmail.
   */
  com.google.protobuf.ByteString
      getPetOwnerEmailBytes();

  /**
   * <code>string timeStart = 2;</code>
   * @return The timeStart.
   */
  java.lang.String getTimeStart();
  /**
   * <code>string timeStart = 2;</code>
   * @return The bytes for timeStart.
   */
  com.google.protobuf.ByteString
      getTimeStartBytes();

  /**
   * <code>string timeFinish = 3;</code>
   * @return The timeFinish.
   */
  java.lang.String getTimeFinish();
  /**
   * <code>string timeFinish = 3;</code>
   * @return The bytes for timeFinish.
   */
  com.google.protobuf.ByteString
      getTimeFinishBytes();

  /**
   * <code>string postalCode = 4;</code>
   * @return The postalCode.
   */
  java.lang.String getPostalCode();
  /**
   * <code>string postalCode = 4;</code>
   * @return The bytes for postalCode.
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <code>string petType = 5;</code>
   * @return The petType.
   */
  java.lang.String getPetType();
  /**
   * <code>string petType = 5;</code>
   * @return The bytes for petType.
   */
  com.google.protobuf.ByteString
      getPetTypeBytes();

  /**
   * <code>int32 petWeight = 6;</code>
   * @return The petWeight.
   */
  int getPetWeight();

  /**
   * <code>bool petIsVaccinated = 7;</code>
   * @return The petIsVaccinated.
   */
  boolean getPetIsVaccinated();
}
