// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobuf;

/**
 * Protobuf type {@code SearchAnnouncementProto}
 */
public final class SearchAnnouncementProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SearchAnnouncementProto)
    SearchAnnouncementProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchAnnouncementProto.newBuilder() to construct.
  private SearchAnnouncementProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchAnnouncementProto() {
    petOwnerEmail_ = "";
    timeStart_ = "";
    timeFinish_ = "";
    postalCode_ = "";
    petType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchAnnouncementProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchAnnouncementProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            petOwnerEmail_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            timeStart_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            timeFinish_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            postalCode_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            petType_ = s;
            break;
          }
          case 48: {

            petWeight_ = input.readInt32();
            break;
          }
          case 56: {

            petIsVaccinated_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return origin.protobuf.Protobuf.internal_static_SearchAnnouncementProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return origin.protobuf.Protobuf.internal_static_SearchAnnouncementProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            origin.protobuf.SearchAnnouncementProto.class, origin.protobuf.SearchAnnouncementProto.Builder.class);
  }

  public static final int PETOWNEREMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object petOwnerEmail_;
  /**
   * <code>string petOwnerEmail = 1;</code>
   * @return The petOwnerEmail.
   */
  @java.lang.Override
  public java.lang.String getPetOwnerEmail() {
    java.lang.Object ref = petOwnerEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      petOwnerEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string petOwnerEmail = 1;</code>
   * @return The bytes for petOwnerEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPetOwnerEmailBytes() {
    java.lang.Object ref = petOwnerEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      petOwnerEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTART_FIELD_NUMBER = 2;
  private volatile java.lang.Object timeStart_;
  /**
   * <code>string timeStart = 2;</code>
   * @return The timeStart.
   */
  @java.lang.Override
  public java.lang.String getTimeStart() {
    java.lang.Object ref = timeStart_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeStart_ = s;
      return s;
    }
  }
  /**
   * <code>string timeStart = 2;</code>
   * @return The bytes for timeStart.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeStartBytes() {
    java.lang.Object ref = timeStart_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeStart_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEFINISH_FIELD_NUMBER = 3;
  private volatile java.lang.Object timeFinish_;
  /**
   * <code>string timeFinish = 3;</code>
   * @return The timeFinish.
   */
  @java.lang.Override
  public java.lang.String getTimeFinish() {
    java.lang.Object ref = timeFinish_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeFinish_ = s;
      return s;
    }
  }
  /**
   * <code>string timeFinish = 3;</code>
   * @return The bytes for timeFinish.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeFinishBytes() {
    java.lang.Object ref = timeFinish_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeFinish_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTALCODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object postalCode_;
  /**
   * <code>string postalCode = 4;</code>
   * @return The postalCode.
   */
  @java.lang.Override
  public java.lang.String getPostalCode() {
    java.lang.Object ref = postalCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postalCode_ = s;
      return s;
    }
  }
  /**
   * <code>string postalCode = 4;</code>
   * @return The bytes for postalCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPostalCodeBytes() {
    java.lang.Object ref = postalCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postalCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PETTYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object petType_;
  /**
   * <code>string petType = 5;</code>
   * @return The petType.
   */
  @java.lang.Override
  public java.lang.String getPetType() {
    java.lang.Object ref = petType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      petType_ = s;
      return s;
    }
  }
  /**
   * <code>string petType = 5;</code>
   * @return The bytes for petType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPetTypeBytes() {
    java.lang.Object ref = petType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      petType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PETWEIGHT_FIELD_NUMBER = 6;
  private int petWeight_;
  /**
   * <code>int32 petWeight = 6;</code>
   * @return The petWeight.
   */
  @java.lang.Override
  public int getPetWeight() {
    return petWeight_;
  }

  public static final int PETISVACCINATED_FIELD_NUMBER = 7;
  private boolean petIsVaccinated_;
  /**
   * <code>bool petIsVaccinated = 7;</code>
   * @return The petIsVaccinated.
   */
  @java.lang.Override
  public boolean getPetIsVaccinated() {
    return petIsVaccinated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petOwnerEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, petOwnerEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStart_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeStart_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeFinish_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timeFinish_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postalCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, postalCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, petType_);
    }
    if (petWeight_ != 0) {
      output.writeInt32(6, petWeight_);
    }
    if (petIsVaccinated_ != false) {
      output.writeBool(7, petIsVaccinated_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petOwnerEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, petOwnerEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStart_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeStart_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeFinish_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timeFinish_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(postalCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, postalCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(petType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, petType_);
    }
    if (petWeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, petWeight_);
    }
    if (petIsVaccinated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, petIsVaccinated_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof origin.protobuf.SearchAnnouncementProto)) {
      return super.equals(obj);
    }
    origin.protobuf.SearchAnnouncementProto other = (origin.protobuf.SearchAnnouncementProto) obj;

    if (!getPetOwnerEmail()
        .equals(other.getPetOwnerEmail())) return false;
    if (!getTimeStart()
        .equals(other.getTimeStart())) return false;
    if (!getTimeFinish()
        .equals(other.getTimeFinish())) return false;
    if (!getPostalCode()
        .equals(other.getPostalCode())) return false;
    if (!getPetType()
        .equals(other.getPetType())) return false;
    if (getPetWeight()
        != other.getPetWeight()) return false;
    if (getPetIsVaccinated()
        != other.getPetIsVaccinated()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PETOWNEREMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getPetOwnerEmail().hashCode();
    hash = (37 * hash) + TIMESTART_FIELD_NUMBER;
    hash = (53 * hash) + getTimeStart().hashCode();
    hash = (37 * hash) + TIMEFINISH_FIELD_NUMBER;
    hash = (53 * hash) + getTimeFinish().hashCode();
    hash = (37 * hash) + POSTALCODE_FIELD_NUMBER;
    hash = (53 * hash) + getPostalCode().hashCode();
    hash = (37 * hash) + PETTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPetType().hashCode();
    hash = (37 * hash) + PETWEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getPetWeight();
    hash = (37 * hash) + PETISVACCINATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPetIsVaccinated());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static origin.protobuf.SearchAnnouncementProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static origin.protobuf.SearchAnnouncementProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static origin.protobuf.SearchAnnouncementProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static origin.protobuf.SearchAnnouncementProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(origin.protobuf.SearchAnnouncementProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SearchAnnouncementProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SearchAnnouncementProto)
      origin.protobuf.SearchAnnouncementProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return origin.protobuf.Protobuf.internal_static_SearchAnnouncementProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return origin.protobuf.Protobuf.internal_static_SearchAnnouncementProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              origin.protobuf.SearchAnnouncementProto.class, origin.protobuf.SearchAnnouncementProto.Builder.class);
    }

    // Construct using origin.protobuf.SearchAnnouncementProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      petOwnerEmail_ = "";

      timeStart_ = "";

      timeFinish_ = "";

      postalCode_ = "";

      petType_ = "";

      petWeight_ = 0;

      petIsVaccinated_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return origin.protobuf.Protobuf.internal_static_SearchAnnouncementProto_descriptor;
    }

    @java.lang.Override
    public origin.protobuf.SearchAnnouncementProto getDefaultInstanceForType() {
      return origin.protobuf.SearchAnnouncementProto.getDefaultInstance();
    }

    @java.lang.Override
    public origin.protobuf.SearchAnnouncementProto build() {
      origin.protobuf.SearchAnnouncementProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public origin.protobuf.SearchAnnouncementProto buildPartial() {
      origin.protobuf.SearchAnnouncementProto result = new origin.protobuf.SearchAnnouncementProto(this);
      result.petOwnerEmail_ = petOwnerEmail_;
      result.timeStart_ = timeStart_;
      result.timeFinish_ = timeFinish_;
      result.postalCode_ = postalCode_;
      result.petType_ = petType_;
      result.petWeight_ = petWeight_;
      result.petIsVaccinated_ = petIsVaccinated_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof origin.protobuf.SearchAnnouncementProto) {
        return mergeFrom((origin.protobuf.SearchAnnouncementProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(origin.protobuf.SearchAnnouncementProto other) {
      if (other == origin.protobuf.SearchAnnouncementProto.getDefaultInstance()) return this;
      if (!other.getPetOwnerEmail().isEmpty()) {
        petOwnerEmail_ = other.petOwnerEmail_;
        onChanged();
      }
      if (!other.getTimeStart().isEmpty()) {
        timeStart_ = other.timeStart_;
        onChanged();
      }
      if (!other.getTimeFinish().isEmpty()) {
        timeFinish_ = other.timeFinish_;
        onChanged();
      }
      if (!other.getPostalCode().isEmpty()) {
        postalCode_ = other.postalCode_;
        onChanged();
      }
      if (!other.getPetType().isEmpty()) {
        petType_ = other.petType_;
        onChanged();
      }
      if (other.getPetWeight() != 0) {
        setPetWeight(other.getPetWeight());
      }
      if (other.getPetIsVaccinated() != false) {
        setPetIsVaccinated(other.getPetIsVaccinated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      origin.protobuf.SearchAnnouncementProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (origin.protobuf.SearchAnnouncementProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object petOwnerEmail_ = "";
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @return The petOwnerEmail.
     */
    public java.lang.String getPetOwnerEmail() {
      java.lang.Object ref = petOwnerEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        petOwnerEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @return The bytes for petOwnerEmail.
     */
    public com.google.protobuf.ByteString
        getPetOwnerEmailBytes() {
      java.lang.Object ref = petOwnerEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        petOwnerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @param value The petOwnerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setPetOwnerEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      petOwnerEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetOwnerEmail() {
      
      petOwnerEmail_ = getDefaultInstance().getPetOwnerEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string petOwnerEmail = 1;</code>
     * @param value The bytes for petOwnerEmail to set.
     * @return This builder for chaining.
     */
    public Builder setPetOwnerEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      petOwnerEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeStart_ = "";
    /**
     * <code>string timeStart = 2;</code>
     * @return The timeStart.
     */
    public java.lang.String getTimeStart() {
      java.lang.Object ref = timeStart_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStart_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeStart = 2;</code>
     * @return The bytes for timeStart.
     */
    public com.google.protobuf.ByteString
        getTimeStartBytes() {
      java.lang.Object ref = timeStart_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeStart = 2;</code>
     * @param value The timeStart to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStart(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeStart = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStart() {
      
      timeStart_ = getDefaultInstance().getTimeStart();
      onChanged();
      return this;
    }
    /**
     * <code>string timeStart = 2;</code>
     * @param value The bytes for timeStart to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStartBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeStart_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeFinish_ = "";
    /**
     * <code>string timeFinish = 3;</code>
     * @return The timeFinish.
     */
    public java.lang.String getTimeFinish() {
      java.lang.Object ref = timeFinish_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeFinish_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeFinish = 3;</code>
     * @return The bytes for timeFinish.
     */
    public com.google.protobuf.ByteString
        getTimeFinishBytes() {
      java.lang.Object ref = timeFinish_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeFinish_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeFinish = 3;</code>
     * @param value The timeFinish to set.
     * @return This builder for chaining.
     */
    public Builder setTimeFinish(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeFinish_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeFinish = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeFinish() {
      
      timeFinish_ = getDefaultInstance().getTimeFinish();
      onChanged();
      return this;
    }
    /**
     * <code>string timeFinish = 3;</code>
     * @param value The bytes for timeFinish to set.
     * @return This builder for chaining.
     */
    public Builder setTimeFinishBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeFinish_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object postalCode_ = "";
    /**
     * <code>string postalCode = 4;</code>
     * @return The postalCode.
     */
    public java.lang.String getPostalCode() {
      java.lang.Object ref = postalCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postalCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string postalCode = 4;</code>
     * @return The bytes for postalCode.
     */
    public com.google.protobuf.ByteString
        getPostalCodeBytes() {
      java.lang.Object ref = postalCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postalCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string postalCode = 4;</code>
     * @param value The postalCode to set.
     * @return This builder for chaining.
     */
    public Builder setPostalCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      postalCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string postalCode = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostalCode() {
      
      postalCode_ = getDefaultInstance().getPostalCode();
      onChanged();
      return this;
    }
    /**
     * <code>string postalCode = 4;</code>
     * @param value The bytes for postalCode to set.
     * @return This builder for chaining.
     */
    public Builder setPostalCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      postalCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object petType_ = "";
    /**
     * <code>string petType = 5;</code>
     * @return The petType.
     */
    public java.lang.String getPetType() {
      java.lang.Object ref = petType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        petType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string petType = 5;</code>
     * @return The bytes for petType.
     */
    public com.google.protobuf.ByteString
        getPetTypeBytes() {
      java.lang.Object ref = petType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        petType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string petType = 5;</code>
     * @param value The petType to set.
     * @return This builder for chaining.
     */
    public Builder setPetType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      petType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string petType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetType() {
      
      petType_ = getDefaultInstance().getPetType();
      onChanged();
      return this;
    }
    /**
     * <code>string petType = 5;</code>
     * @param value The bytes for petType to set.
     * @return This builder for chaining.
     */
    public Builder setPetTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      petType_ = value;
      onChanged();
      return this;
    }

    private int petWeight_ ;
    /**
     * <code>int32 petWeight = 6;</code>
     * @return The petWeight.
     */
    @java.lang.Override
    public int getPetWeight() {
      return petWeight_;
    }
    /**
     * <code>int32 petWeight = 6;</code>
     * @param value The petWeight to set.
     * @return This builder for chaining.
     */
    public Builder setPetWeight(int value) {
      
      petWeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 petWeight = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetWeight() {
      
      petWeight_ = 0;
      onChanged();
      return this;
    }

    private boolean petIsVaccinated_ ;
    /**
     * <code>bool petIsVaccinated = 7;</code>
     * @return The petIsVaccinated.
     */
    @java.lang.Override
    public boolean getPetIsVaccinated() {
      return petIsVaccinated_;
    }
    /**
     * <code>bool petIsVaccinated = 7;</code>
     * @param value The petIsVaccinated to set.
     * @return This builder for chaining.
     */
    public Builder setPetIsVaccinated(boolean value) {
      
      petIsVaccinated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool petIsVaccinated = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPetIsVaccinated() {
      
      petIsVaccinated_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SearchAnnouncementProto)
  }

  // @@protoc_insertion_point(class_scope:SearchAnnouncementProto)
  private static final origin.protobuf.SearchAnnouncementProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new origin.protobuf.SearchAnnouncementProto();
  }

  public static origin.protobuf.SearchAnnouncementProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchAnnouncementProto>
      PARSER = new com.google.protobuf.AbstractParser<SearchAnnouncementProto>() {
    @java.lang.Override
    public SearchAnnouncementProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchAnnouncementProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchAnnouncementProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchAnnouncementProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public origin.protobuf.SearchAnnouncementProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

